---
# En esta task se lanzan 5 scripts con diferentes usos: el persistent-volume incluye la configuración del volumen persistente a utilizar, integrado en este caso con el NFS; el persistent-volume-claim, para el volumen que usará el pod; y 3 archivos destinados al despliegue de la aplicación Prometheus. 
- name: Se copian todos los archivos de los despliegues
  copy:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
    mode: '0644'
  with_items:
    - persistent-volume.yml
    - persistent-volume-claim.yml
    - PrometheusConfigMap.yml
    - PrometheusDeployment.yml
    - PrometheusRole.yml
  become: yes

- name: Se crea el namespace
  shell: "kubectl create namespace application"
  become: yes

- name: Se lanzan los despliegues
  shell: "kubectl apply -f /root/{{ item }}"
  with_items:
    - persistent-volume.yml
    - persistent-volume-claim.yml
    - PrometheusConfigMap.yml
    - PrometheusDeployment.yml
    - PrometheusRole.yml
  become: yes
