---

- name: Copiando los archivos de las Aplicaciones
  copy:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
    mode: '0644'
  with_items:
    - persistent-volume.yml
    - persistent-volume-claim.yml
    - PrometheusConfigMap.yml
    - PrometheusDeployment.yml
    - PrometheusRole.yml
  become: yes

- name: Creando namespace
  shell: "kubectl create namespace application"
  become: yes

- name: Se aplican los volumenes
  shell: "kubectl apply -f /root/{{ item }}"
  register: kubectl_apply_app
  with_items:
    - persistent-volume.yml
    - persistent-volume-claim.yml
    - PrometheusConfigMap.yml
    - PrometheusDeployment.yml
    - PrometheusRole.yml
  become: yes